=== Adam3826/projetTuxZodjihokMoussolna/tux/xsd/profil.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<xs:schema xmlns:targetNamespace="http://myGame/tux"
           xmlns:pf="http://myGame/tux"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="profil" type="pf:Profile"/>
        <xs:complexType name="Profile">
            <xs:sequence>
                <xs:element name="nom" type="xs:string"/>
                <xs:element name="avatar" type="xs:string"/>
                <xs:element name="anniversaire" type="xs:date"/>
                <xs:element name="parties" type="pf:Parties"/>
            </xs:sequence>
            
        </xs:complexType>
        
        <xs:complexType name="Parties">
            <xs:sequence>
                <xs:element name="partie" type="pf:Partie" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>  
        </xs:complexType>
        
        
        
         <xs:complexType name="Partie">
            <xs:sequence>
                <xs:element name="mot" type="pf:Mot"/>
                <xs:element name="temps" type="xs:double" minOccurs="0"/>
            </xs:sequence>  
            <xs:attribute name="date" type="xs:date" use="required"/>
            <xs:attribute name="trouvÃ©" type="xs:string"  use ="optional"/>
        </xs:complexType>
        
        <xs:complexType name="Mot">
        <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="niveau" type="xs:int" use="required"/>
                </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
        

</xs:schema>

=== Adam3826/projetTuxZodjihokMoussolna/tux/xml/profil_.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<profil
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../../../src/pro_tux/profil.xsd'>
    <nom></nom>
    <avatar></avatar>
    <anniversaire></anniversaire>
    <parties>
        <partie date="" trouvé="">
            <mot niveau=""></mot>
            <temps></temps>
        </partie>
        <partie date="" trouvé="">
            <mot niveau=""></mot>
            <temps></temps>
        </partie>
        <partie date="" trouvé="">
            <mot niveau=""></mot>
            <temps></temps>
        </partie>
    </parties>

</profil>

=== Adam3826/projetTuxZodjihokMoussolna/tux/src/XML/profil.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<pf:profil
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pf="http://myGame/tux"
    xsi:schemaLocation="http://myGame/tux ../xsd/profil.xsd">
    <pf:nom>Alban</pf:nom>
    <pf:avatar>conan.jpg</pf:avatar>
    <pf:anniversaire>2006-05-08</pf:anniversaire>
    <pf:parties>
        <pf:partie date="2013-12-10" >
            <pf:mot niveau="1">cle</pf:mot>
            <pf:temps>20.0</pf:temps>
        </pf:partie>
        <pf:partie date="2013-12-11" trouvé="75%">
            <pf:mot niveau="2">indice</pf:mot>
            
        </pf:partie>
        <pf:partie date="2013-12-11" trouvé="">
            <pf:mot niveau="2">indice</pf:mot>
            <pf:temps>20.0</pf:temps>
        </pf:partie>
    </pf:parties>

</pf:profil>
